### ISSUE TITLE
MIE as a multi-user application - need to make sure we handle (blocking or coping) with multiple users running workflows and edits on the same MIE assets at the same time.

### ISSUE THREAD

**Issue by tomgilman** [aburkleaux-amazon/aws-media-insights-engine#25] opened 2020-04-09 23:29 UTC
Good opportunity for partner.

**Comment by aburkleaux-amazon** [comment] 2020-04-09 23:47
This is probably not a GUI, I had it mis-filed in the doc.  It requires creating a lock on an asset.  This doesn't mean it has to be implemented in MIE infrastructure.

**Comment by aburkleaux-amazon** [comment] 2020-04-16 04:02
Duplicate of #37

**Closed** 2020-04-16 04:02 UTC
Labels: duplicate
